import { describe, it, expect, beforeEach } from 'vitest';
import { TypeScriptAdapter } from './typescript.adapter';
import type { ApplicationDefinition, ResourceDefinitionForCodegen } from '../../codegen-types';

describe('TypeScriptAdapter', () => {
  let adapter: TypeScriptAdapter;

  const createResource = (
    overrides: Partial<ResourceDefinitionForCodegen> = {},
  ): ResourceDefinitionForCodegen => ({
    name: 'Category',
    displayName: 'Category',
    description: 'A product category',
    fields: [
      { name: 'name', displayName: 'Name', type: 'string', required: true },
      { name: 'description', displayName: 'Description', type: 'text', required: false },
      { name: 'active', displayName: 'Active', type: 'boolean', required: true },
    ],
    ...overrides,
  });

  const createDefinition = (
    resources: ResourceDefinitionForCodegen[] = [createResource()],
  ): ApplicationDefinition => ({
    name: 'TestApp',
    resources,
    components: [],
  });

  beforeEach(() => {
    adapter = new TypeScriptAdapter();
  });

  it('should have correct framework', () => {
    expect(adapter.framework).toBe('typescript');
  });

  it('should return file extensions', () => {
    expect(adapter.getFileExtensions()).toContain('.ts');
  });

  describe('compile', () => {
    it('should generate interface for a resource', () => {
      const result = adapter.compile(createDefinition(), { framework: 'typescript' });

      expect(result.success).toBe(true);
      expect(result.files).toHaveLength(1);
      expect(result.files[0].content).toContain('export interface Category {');
    });

    it('should generate correct field types', () => {
      const result = adapter.compile(createDefinition(), { framework: 'typescript' });
      const content = result.files[0].content;

      expect(content).toContain('name: string;');
      expect(content).toContain('description?: string;');
      expect(content).toContain('active: boolean;');
    });

    it('should mark optional fields with ?', () => {
      const result = adapter.compile(createDefinition(), { framework: 'typescript' });
      const content = result.files[0].content;

      expect(content).toContain('description?:');
      expect(content).not.toMatch(/name\?:/);
    });

    it('should generate CreateInput type', () => {
      const result = adapter.compile(createDefinition(), { framework: 'typescript' });
      const content = result.files[0].content;

      expect(content).toContain(
        "export type CategoryCreateInput = Omit<Category, 'id' | 'createdAt' | 'updatedAt'>;",
      );
    });

    it('should generate UpdateInput type', () => {
      const result = adapter.compile(createDefinition(), { framework: 'typescript' });
      const content = result.files[0].content;

      expect(content).toContain('export type CategoryUpdateInput = Partial<CategoryCreateInput>;');
    });

    it('should handle all field types', () => {
      const resource = createResource({
        fields: [
          { name: 'f_string', displayName: 'String', type: 'string', required: true },
          { name: 'f_text', displayName: 'Text', type: 'text', required: true },
          { name: 'f_bool', displayName: 'Bool', type: 'boolean', required: true },
          { name: 'f_int', displayName: 'Int', type: 'integer', required: true },
          { name: 'f_float', displayName: 'Float', type: 'float', required: true },
          { name: 'f_time', displayName: 'Time', type: 'timestamp', required: true },
          { name: 'f_json', displayName: 'Json', type: 'json', required: true },
          { name: 'f_enum', displayName: 'Enum', type: 'enum', required: true },
        ],
      });

      const result = adapter.compile(createDefinition([resource]), { framework: 'typescript' });
      const content = result.files[0].content;

      expect(content).toContain('f_string: string');
      expect(content).toContain('f_text: string');
      expect(content).toContain('f_bool: boolean');
      expect(content).toContain('f_int: number');
      expect(content).toContain('f_float: number');
      expect(content).toContain('f_time: Date');
      expect(content).toContain('f_json: Record<string, unknown>');
      expect(content).toContain('f_enum: string');
    });

    it('should generate comments when requested', () => {
      const result = adapter.compile(createDefinition(), {
        framework: 'typescript',
        includeComments: true,
      });
      const content = result.files[0].content;

      expect(content).toContain('/**');
      expect(content).toContain('A product category');
      expect(content).toContain('Generated by DevFlow Platform');
    });

    it('should not generate comments by default', () => {
      const result = adapter.compile(createDefinition(), { framework: 'typescript' });
      const content = result.files[0].content;

      expect(content).not.toContain('/** Generated');
    });

    it('should handle multiple resources', () => {
      const resources = [
        createResource({
          name: 'Category',
          fields: [{ name: 'name', displayName: 'Name', type: 'string', required: true }],
        }),
        createResource({
          name: 'Product',
          fields: [{ name: 'title', displayName: 'Title', type: 'string', required: true }],
        }),
      ];

      const result = adapter.compile(createDefinition(resources), { framework: 'typescript' });

      expect(result.files).toHaveLength(3); // 2 resource files + 1 index
      expect(result.files[2].path).toBe('index.ts');
      expect(result.files[2].content).toContain('Category');
      expect(result.files[2].content).toContain('Product');
    });

    it('should use output prefix', () => {
      const result = adapter.compile(createDefinition(), {
        framework: 'typescript',
        outputPrefix: 'src/types',
      });

      expect(result.files[0].path).toBe('src/types/category.ts');
    });

    it('should set correct metadata', () => {
      const result = adapter.compile(createDefinition(), { framework: 'typescript' });

      expect(result.metadata.framework).toBe('typescript');
      expect(result.metadata.resourceCount).toBe(1);
      expect(result.metadata.componentCount).toBe(0);
      expect(result.metadata.fileCount).toBe(1);
      expect(result.metadata.generatedAt).toBeInstanceOf(Date);
    });
  });
});
